### ISSUE TITLE
Missing Dataset Files?

### ISSUE THREAD

**Issue by Andrew-Brown1** [clairecyq/whos-waldo#1]
Hey there,

I have run into some problems in preprocessing the dataset, could you please help? 

Particularly, I am looking at the 'preprocess/generate_annotations.py' and there seem to be several files that were not included in the dataset that I downloaded using the bash script provided (which is identical to the one outlined in "directory structure" on this website https://whoswaldo.github.io/dataset)

e.g. 'interactive_img_ids.txt' (line 52), 'val_turkers.json', 'test_turkers.json' (line 103), and 'val.txt', 'test.txt' (line 89)

Thanks for any help you can provide. We are looking forward to using the v. cool dataset!

Andrew

**Comment by apoorvkh** [comment]
We actually have already included these files in the repo (in the [./dataset_meta](https://github.com/clairecyq/whos-waldo/tree/80f36249238ce203f81d2493b758302e5d403635/dataset_meta) folder).

So, `meta_dir` ([at line 14](https://github.com/clairecyq/whos-waldo/blob/80f36249238ce203f81d2493b758302e5d403635/preprocess/generate_annotations.py#L14)) refers to that folder and `root_dir` ([at line 13](https://github.com/clairecyq/whos-waldo/blob/80f36249238ce203f81d2493b758302e5d403635/preprocess/generate_annotations.py#L13)) actually refers to the path to our cloned repo.

You're going to want to run `python preprocess/generate_annotations.py` from the root of our repo.

Apologies if this was confusing. Please let me know if that didn't resolve your issue.

**Comment by Andrew-Brown1** [comment]
great, thanks!
