### ISSUE TITLE
For extracted image features

### ISSUE THREAD

**Issue by lukem209** [clairecyq/whos-waldo#2]
Hi, thank you for your nice work.
Is it possible to provide a link to download your extracted image features for creating the imgdb?
Thank you!

**Comment by EstherBear** [comment]
Hi, have you extracted the image features?
I've extracted the image features from bounding boxes with this [repo](https://github.com/MILVLG/bottom-up-attention.pytorch), but it resulted in NaN when I used these features to train.

**Comment by apoorvkh** [comment]
Sorry for the delayed response -- this message is for posterity. We don't have these features available anymore.



Please refer to this PR for some additional code that can be helpful for recreating the imgdb: https://github.com/clairecyq/whos-waldo/pull/4
